on: push
name: TestOnPush
jobs: 
  gitHubActionForPytest:
    name: Run PyTest on Push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
           python3 -m pip install setuptools
           python3 setup.py --verbose develop
      - name: Test with pytest
        run: |
          pip install pytest 
          pytest -sv
