on: push
name: TestOnPush
jobs: 
  gitHubActionForPytest:
    name: Run PyTest on Push
    runs-on: ubuntu-latest
    steps:      
      - name: Install Python3-dev
        run: sudo apt-get update && sudo apt-get install -y python3-dev
      - uses: actions/checkout@master
      - name: GitHub action for pytest
        uses: cclauss/GitHub-Action-for-pytest@master
        with:
          args: python setup.py --verbose develop && coverage run -m pytest -sv && coverage html
